# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63c13396c80730e8a19593698b7b31a8028da4a3d7759e0d1598a9a15b3f76f9fa6b12891b27c355135065b74c2817885718b7bd0363908e758f8a3f9a7a8d37

test:
  secret_key_base: bee6bde73921564d6c5f02715cb615b6e312d213f03ffb1d63c3f2851c32fde453f94353aa7d719442cea08776483249906c37eaab9ba947cf6211ed01cf7ea7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
